name = "nearby4u"  
type = "javascript"

[build]
  command = "npm run build"  
  pages_build_output_dir = "dist"  


[[publish]]
  name = "nearby4uworker"  
  cmd = "wrangler publish"   


[[bindings]]
  type = "worker"
  name = "nearby4uworker" 
  worker = "nearby4u-worker" 
