name = "https://renew.yindin777.workers.dev/"  # <--- Use your actual worker name here
type = "javascript"
account_id = "310e549bbc8846e19ec8b3bd662d5f00"

[build]
  command = "npm run build"
  upload = {
    main = "dist/worker.js"
  }

[[publish]]
  name = "https://renew.yindin777.workers.dev/"  # <--- Use your actual worker name here
  cmd = "wrangler publish"
  
