[env.production]
services = [
  { binding = "HizmetBaglama", service = "nearby4u" }, 
]

workers_ai = [
  { binding = "nearby4u", value = "Workers AI Catalog" }, 
  { binding = "@cf/meta/llama-3.2-11b-vision-instruct", value = "Workers AI Catalog" } 
]
