name = "nearby4u"  
type = "javascript"

[build]
  command = "npm run build"  
  pages_build_output_dir = "dist"  


[[publish]]
  name = "isleyen"  
  cmd = "wrangler publish"   


[[bindings]]
  type = "worker"
  name = "isleyen"
  worker = "dist/worker.js"
