name = "my-nearby-worker"  # <--- Use your actual worker name here
type = "javascript"
account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"

[build]
  command = "npm run build"
  upload = {
    main = "dist/worker.js"
  }

[[publish]]
  name = "my-nearby-worker"  # <--- Use your actual worker name here
  cmd = "wrangler publish"
  
