name = "renew"
type = "javascript"
account_id = "310e549bbc8846e19ec8b3bd662d5f00"

[build]
  command = "npm run build"
  upload = { main = "dist/worker.js" }

[[publish]]
  name = "renew"
  cmd = "wrangler publish"
